const throwError = () => {
  throw new Error("This is my error!!!");
};

export default throwError;
